
/*
 * action types
 */
const ActionsTypes={
  //
  SERVER_CONNECT:'SERVER_CONNECT',
  SERVER_CONNECT_NET_INFO_CHANGE:'SERVER_CONNECT_NET_INFO_CHANGE',

  //
  STORE_SET:'STORE_SET',
  STORE_GET:'STORE_GET',
  STORE_REMOVE:'STORE_REMOVE',
  //
  APP_STATE_SET: 'APP_STATE_SET',
  APP_STATE_DIRECT_SET : 'APP_STATE_DIRECT_SET',
  APP_STATE_LIST:{
    LOADING:'LOADING',
    RUNNING:'RUNNING',
  },
  APP_STATE_DIRECT_LIST:{
    PORTRAIT:'PORTRAIT',
    LANDSCAPE:'LANDSCAPE',
    UNKNOWN: 'UNKNOWN'
  },
  /** use for request to actions
  *
  */
  REQUEST_SUBTYPE:{
    REQUEST:'REQUEST',
    ERROR:'ERROR',
    SUCCESS:'SUCCESS',
  },
  //
}

module.exports= ActionsTypes
